### ISSUE TITLE
How to use with rspec?

### ISSUE THREAD

**Issue by s2t2** [ConradIrwin/pry-rescue#98]
This gem sounds really helpful. But it seems either I'm not sure how to use it with rspec, or maybe it isn't working as expected. I ran `bundle exec rescue rspec spec/` and got the following result. 

```
From: /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb @ line 87 :

    82:     def self.failure_notifier=(callable)
    83:       thread_local_data[:failure_notifier] = callable
    84:     end
    85: 
    86:     # @private
 => 87:     DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
    88: 
    89:     # @api private
    90:     def self.failure_notifier
    91:       thread_local_data[:failure_notifier] || DEFAULT_FAILURE_NOTIFIER
    92:     end

RSpec::Expectations::ExpectationNotMetError: expected nil to be a kind of Hash
from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>'
```

How can I get back into the context of my rspec test?

**Comment by ConradIrwin** [comment]
Hi MJ,I'm unable to spend time on this gem right now, if you'd like to debug the problem, please feel free — it's all written in ruby, so it shouldn't be too hard if you have some time.ConradSent via SuperhumanOn Sun, May 22, 2016 at 7:54 PM, MJ Rossetti<notifications@github.com>wrote:This gem sounds really helpful. But it seems either I'm not sure how to use it with rspec, or maybe it isn't working as expected. I ran bundle exec rescue rspec spec/ and got the following result. 

From: /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb @ line 87 :

    82:     def self.failure_notifier=(callable)
    83:       thread_local_data[:failure_notifier] = callable
    84:     end
    85: 
    86:     # @private
 => 87:     DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
    88: 
    89:     # @api private
    90:     def self.failure_notifier
    91:       thread_local_data[:failure_notifier] || DEFAULT_FAILURE_NOTIFIER
    92:     end

RSpec::Expectations::ExpectationNotMetError: expected nil to be a kind of Hash
from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>'


How can I get back into the context of my rspec test?

**Comment by bartoszkopinski** [comment]
@s2t2 Try using:
```
SPEC_OPTS="-r pry-rescue/rspec" PRY_RESCUE_RAILS=true bundle exec rescue rspec spec
```
or
```
PRY_RESCUE_RAILS=true bundle exec rescue rspec spec
```

**Comment by gerrywastaken** [comment]
Running into the same issue, but neither of these worked for me. Will look into the pry-rescue code when I have some free time.

**Comment by PhilT** [comment]
did you add the pry-stack_explorer? I saw this before I'd added that gem as well.

**Comment by TylerRick** [comment]
Ran into the same problem. Adding `pry-stack_explorer` worked for me and caused it to automatically show the correct failure location in the actual test file instead of this useless stack frame:

```
From: ~/.gem/ruby/2.4.5/gems/rspec-support-3.8.0/lib/rspec/support.rb @ line 97 :

...
     96:     # @private
 =>  97:     DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
     98: 
...
```

I noticed this question in `pry-rescue.gemspec:17`:
```ruby
  s.add_development_dependency 'pry-stack_explorer' # upgrade to regular dep?
```

Any reason not to upgrade `pry-stack_explore` to a run-time dependency so it just works out of the box and people don't get bit by this? Is it because it only supports Rubinius and MRI Ruby and `pry-rescue` supports other Rubys (I don't know)?

At the very least, how about adding the run-time requirement to `lib/pry-rescue/rspec.rb` like I see we have in `lib/pry-rescue/peek.rb:12`:
```ruby
      raise "pry-stack_explorer is not installed"
```
?

Also... could anyone explain _how_ simply having `pry-stack_explore` loaded causes this to automatically detect the correct frame? Pretty cool....

(@bartoszkopinski, `PRY_RESCUE_RAILS=true` isn't necessary for rspec. That adds a Rack middleware and is only useful for adding rescue to `rails server`.)
